### ISSUE TITLE
picguard@1.0.0+295: decompress error

### ISSUE THREAD

**Issue by kjxbyz** [picguard/scoop-bucket#1]
Relates to https://github.com/ScoopInstaller/Extras/issues/13444.

**Comment by kjxbyz** [comment]
can be fixed by install another version of innounp

```
scoop uninstall innounp
scoop bucket add versions
scoop install versions/innounp-unicode
```

and this is just a temporary way to fix, seem like the latest version of scoop trying to fix this issue https://github.com/ScoopInstaller/Scoop/pull/6028, but not successful in this issue https://github.com/ScoopInstaller/Scoop/issues/6040

**Comment by qwertyhjklxyz** [comment]
@kjxbyz Since you are calling `picguard.exe` in `Installer`, there is no need to decompress it with innounp.
By the way, decompression fails because one of the decompressed files has the same name as the original file.

**Comment by kjxbyz** [comment]
@qwertyhjklxyz Is there a file called picguard.exe in the unzipped files, or is there a file called PicGuard.exe in the unzipped files because of the following code?

https://github.com/picguard/picguard/blob/d26894f82a8cba4f5b45d417c2aeca67c95a9f0b/windows/runner/Runner.rc#L97C20-L97C36

**Comment by qwertyhjklxyz** [comment]
You can rename the downloaded file to something else.
```
"url": "https://github.com/picguard/picguard/releases/download/v1.0.0+298/picguard_1.0.0+298_windows_x86_64.exe#/PicGuardSetup.exe",
```

**Comment by qwertyhjklxyz** [comment]
It is recommended to remove the `installer` and `uninstaller` and let scoop control the software installation.

**Comment by kjxbyz** [comment]
@qwertyhjklxyz Thank you very much.
